### ISSUE TITLE
Memory Error while taking screenshots

### ISSUE THREAD

**Issue by sco1** [sco1/skyportal#11]
At some point recently I seemed to have broken the screenshotting capability:

```py
Traceback (most recent call last):
  File "code.py", line 81, in <module>
  File "skyportal/displaylib.py", line 534, in process_touch
  File "skyportal/displaylib.py", line 171, in check_fire
  File "skyportal/displaylib.py", line 94, in take_screenshot
  File "adafruit_bitmapsaver.py", line 161, in save_pixels
  File "adafruit_bitmapsaver.py", line 159, in save_pixels
  File "adafruit_bitmapsaver.py", line 107, in _write_pixels
MemoryError: memory allocation failed, allocating 2048 bytes
```

Checking the memory stats before saving the bitmap seems to show there's plenty of memory left, even before manually GCing:

```
Free 23408 Alloc 192976
GC Free 25232 Alloc 191152
```

So I'm not sure where the issue lies.

**Comment by sco1** [comment]
We start to run into memory errors after f80fe457adb3db13a63fbd71eda748748a479b77 Commenting out the info box initialization seems to solve the problem.

Checking on the memory usage right before we try to save the screenshot with 20 aircraft on screen:

```
With Info box init: Pre SS Free 24960 Alloc 191936
No info box init:   Pre SS Free 50288 Alloc 166608
```

**Comment by sco1** [comment]
This seems to be more of a general issue than I realized, since we're no longer able to save the map tiles either. I just discovered [this guide](https://learn.adafruit.com/Memory-saving-tips-for-CircuitPython?view=all) that I'll give a read through and see if I can make some changes to alleviate all of these problems.

**Comment by sco1** [comment]
With 912297ec30015672bcf2e7b48b2810d97216c1f3 this might possibly be fixed? It seems to work ok now but with OpenSky currently down I can't test with aircraft on screen.

**Comment by sco1** [comment]
I've decided to fix this by just removing the screenshot UI altogether for the next release 😄 

With the memory constraints everywhere else it ended up being easier to not have to worry about the additional UI overhead for something that's mostly used to debug. If I need to do that I can just edit in the line of code to do so.
